<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>inventory.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="inventory.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="inventory.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="inventory.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
